# This is a basic workflow to help you get started with Actions

name: CI for dev

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
            toolchain: stable

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable -y
        sudo apt-get update -y
        sudo apt-get install swi-prolog-nox libpcre3 -y

    - name: Download LinuxDeploy AppImage
      run: wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage

    - name: Give Linuxdeploy exec permissions
      run: chmod +x linuxdeploy-x86_64.AppImage

    - name: Run the build script
      run: ./build_script.sh canary

    - name: Rename AppImage
      run: mv "TerminusDB-$(echo $GITHUB_SHA | cut -c 1-7)-x86_64.AppImage" TerminusDB-amd64.AppImage

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: TerminusDB-amd64.AppImage
        path: TerminusDB-amd64.AppImage

    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
          with:
            tag_name: dev

    - name: Create a Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dev
        prerelease: true
        files: TerminusDB-amd64.AppImage
